// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using week14.Data;

namespace week14.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("week14.Models.Cursus", b =>
                {
                    b.Property<int>("cursusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cursusNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("cursusId");

                    b.ToTable("Cursus");
                });

            modelBuilder.Entity("week14.Models.Student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cursusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("lengte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("studentNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("studentId");

                    b.HasIndex("cursusId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("week14.Models.Student", b =>
                {
                    b.HasOne("week14.Models.Cursus", "cursus")
                        .WithMany("student")
                        .HasForeignKey("cursusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cursus");
                });

            modelBuilder.Entity("week14.Models.Cursus", b =>
                {
                    b.Navigation("student");
                });
#pragma warning restore 612, 618
        }
    }
}
