// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc10B;

namespace Mvc10B.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20201123144223_EersteMigration")]
    partial class EersteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Mvc10B.StudentDB", b =>
                {
                    b.Property<int>("StudentNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAdres")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoorNaam")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("StudentNummer");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
